name: Nightly Test run (Jahia SN)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  integration-tests:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: luxe-jahia-demo
      testrail_project: Demo Site Javascript Module
      pagerduty_incident_service: luxe-jahia-demo-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: luxe
      module_branch: ${{ github.ref }}
