name: Nightly Test run (Jahia RL)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  integration-tests:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee:8
      module_id: luxe-jahia-demo
      testrail_project: Demo Site Javascript Module
      pagerduty_incident_service: keepicker-JahiaRL
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: luxe
      module_branch: ${{ github.ref }}
